(define (my-repl)
  (display "mine>")
  (let ((expr (read)))
    (cond ((eq? expr 'halt)
           (display "Halting")
           (newline))
          (else
            (write (eval expr))
            (newline)
            (my-repl)))))
(my-repl)
