CFLAGS=-Wall -g -lm
all:hello_world fahr_to_cel cel_to_fahr cel_to_fahr fahr_to_cel_v2 fahr_to_cel_rev symbolic_constants file_copying \
		char_counting char_counting_v2 word_counting arrays functions arguments_CallByValue character_arrays\
		lower atoi strlen squeeze temp strcat squeeze2 any sort_search


clean:
	rm -f hello_world
	rm -f fahr_to_cel
	rm -f cel_to_fahr
	rm -f cel_to_fahr
	rm -f fahr_to_cel_v2
	rm -f fahr_to_cel_rev
	rm -f symbolic_constants
	rm -f file_copying
	rm -f char_counting
	rm -f char_counting_v2
	rm -f word_counting
	rm -f arrays
	rm -f functions
	rm -f arguments_CallByValue
	rm -f character_arrays
	rm -f strlen
	rm -f lower
	rm -f atoi
	rm -f a.out
	rm -f squeeze
	rm -f temp
	rm -f strcat
	rm -f squeeze2
	rm -f any
	rm -f sort_search
